# Generated by Django 3.2.4 on 2021-07-19 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comment_listing_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='auctions.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='listings',
            field=models.ManyToManyField(blank=True, null=True, related_name='watchlist', to='auctions.Listing'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
