# Generated by Django 3.2.4 on 2021-06-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_comments_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='category',
            field=models.CharField(default='None', max_length=13),
        ),
        migrations.AddField(
            model_name='listings',
            name='imgUrl',
            field=models.CharField(default='default_img.PNG', max_length=256),
        ),
        migrations.AlterField(
            model_name='bids',
            name='time',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='listings',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
