# Generated by Django 3.2.4 on 2021-07-26 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_bid_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='by',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.DO_NOTHING, to='auctions.user'),
            preserve_default=False,
        ),
    ]
